Repository JuulLabs/tuulbox, pull requests merged in 2024-03, with the labels that each got.

#347 Update binary-compatibility-validator to v0.14.0
  gradle/libs.versions.toml
Labels: maintenance

#345 Deprecate logging library and point at Khronicle
  README.md
  logging-android/src/androidMain/kotlin/AndroidLogger.kt
  logging-ktor-client/src/commonMain/kotlin/TuulboxKtorClientLogger.kt
  logging/src/appleMain/kotlin/AppleSystemLogger.kt
  logging/src/appleMain/kotlin/ConsoleLogger.kt
  logging/src/commonMain/kotlin/Call.kt
  logging/src/commonMain/kotlin/CallListLogger.kt
  logging/src/commonMain/kotlin/ConsoleLogger.kt
  logging/src/commonMain/kotlin/ConstantTagGenerator.kt
  logging/src/commonMain/kotlin/DispatchLogger.kt
  logging/src/commonMain/kotlin/FilterLevelLogger.kt
  logging/src/commonMain/kotlin/FilterLogger.kt
  logging/src/commonMain/kotlin/HideFromStackTraceTag.kt
  logging/src/commonMain/kotlin/Key.kt
  logging/src/commonMain/kotlin/Log.kt
  logging/src/commonMain/kotlin/LogLevel.kt
  logging/src/commonMain/kotlin/Logger.kt
  logging/src/commonMain/kotlin/Metadata.kt
  logging/src/commonMain/kotlin/Sensitivity.kt
  logging/src/commonMain/kotlin/TagGenerator.kt
  logging/src/commonMain/kotlin/TuulboxInternal.kt
  logging/src/jsMain/kotlin/ConsoleLogger.kt
  logging/src/jvmMain/kotlin/ConsoleLogger.kt
Labels: minor

#352 Replace deprecated Gradle `buildDir`
  build.gradle.kts
Labels: maintenance

#353 Simplify `binary-compatibility-validator` setup
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: maintenance

#358 Mark `BroadcastReceiver.onReceive` parameters as non-`null`
  coroutines/src/androidMain/kotlin/flow/BroadcastReceiverFlow.kt
Labels: patch
